### ISSUE TITLE
Unable to selectively apply rules

### ISSUE THREAD

**Issue by Namyalg** [lyxell/logifix#167]
When I run `logifix --in-place --accept=S1128, S1481 --accept-all Test.java`, with the intention of only applying the 2 rules interactively in-place, I see the other rules are applied by default.
Is there anyway I can avoid this ?

**Comment by lyxell** [comment]
Hi @Namyalg
Cool that you're trying out Logifix!

If your intention is to only apply S1128 and S1481 you should skip the `--accept-all` flag as that will override the `--accept` flag.

I.e. try `logifix --in-place --accept=S1128,S1481 Test.java`

Also, make sure to not separate the rules with a space when using the `--accept` flag
i.e. write `S1128,S1481` instead of `S1128, S1481`

Please reopen this issue if this doesn't work!
